#include "src/brain/language/ExternalLlmBackend.h"

namespace yuki::brain::language {

GenerationResult ExternalLlmBackend::generate(const GenerationRequest& request) {
    GenerationResult res;
    res.success = true;
    res.backend = BackendKind::EXTERNAL_LLM;
    res.backendName = name();
    res.confidence = 0.95f;
    res.fluencyScore = 0.92f;
    res.relevanceScore = 0.94f;
    res.safetyScore = 0.98f;
    res.estimatedCost = estimateCost(request);
    res.text = "Response generated by ExternalLlmBackend for prompt: " + request.prompt;
    return res;
}

bool ExternalLlmBackend::available() const {
    return true;
}

float ExternalLlmBackend::estimateCost(const GenerationRequest& request) const {
    return static_cast<float>(request.maxTokens) * 0.00001f;
}

} // namespace yuki::brain::language
