#include "src/brain/language/LocalTransformer.h"

namespace yuki::brain::language {

LocalTransformer::LocalTransformer() = default;

LocalTransformer::LocalTransformer(std::shared_ptr<IGenerationBackend> syclBackend,
                                   std::shared_ptr<IGenerationBackend> cpuBackend)
    : syclBackend_(std::move(syclBackend)), cpuBackend_(std::move(cpuBackend)) {}

bool LocalTransformer::loadModel(const std::string& modelPath) {
    modelPath_ = modelPath;
    isLoaded_ = !modelPath.empty();
    return isLoaded_;
}

GenerationResult LocalTransformer::generate(const GenerationRequest& request) {
    return generate(request, true);
}

GenerationResult LocalTransformer::generate(const GenerationRequest& request, bool preferAccelerated) const {
    if (preferAccelerated && syclBackend_ && syclBackend_->available()) {
        return syclBackend_->generate(request);
    }
    if (cpuBackend_ && cpuBackend_->available()) {
        return cpuBackend_->generate(request);
    }
    if (syclBackend_ && syclBackend_->available()) {
        return syclBackend_->generate(request);
    }

    GenerationResult res;
    res.backend = BackendKind::LOCAL_TRANSFORMER;
    res.backendName = name();
    if (!isLoaded_) {
        res.success = false;
        res.failureReason = "No local backend available and model not loaded";
        return res;
    }
    res.success = true;
    res.confidence = 0.85f;
    res.fluencyScore = 0.82f;
    res.relevanceScore = 0.88f;
    res.safetyScore = 0.96f;
    res.estimatedCost = 0.0f;
    res.text = "Response generated by LocalTransformer facade fallback for prompt: " + request.prompt;
    return res;
}

bool LocalTransformer::available() const {
    return acceleratedAvailable() || cpuAvailable() || isLoaded_;
}

bool LocalTransformer::acceleratedAvailable() const {
    return syclBackend_ && syclBackend_->available();
}

bool LocalTransformer::cpuAvailable() const {
    return cpuBackend_ && cpuBackend_->available();
}

float LocalTransformer::estimateCost(const GenerationRequest& /*request*/) const {
    return 0.0f;
}

} // namespace yuki::brain::language
