#include "src/brain/language/LocalTransformer.h"

namespace yuki::brain::language {

LocalTransformer::LocalTransformer() = default;

bool LocalTransformer::loadModel(const std::string& modelPath) {
    modelPath_ = modelPath;
    isLoaded_ = !modelPath.empty();
    return isLoaded_;
}

GenerationResult LocalTransformer::generate(const GenerationRequest& request) {
    GenerationResult res;
    res.backend = BackendKind::LOCAL_TRANSFORMER;
    res.backendName = name();
    if (!isLoaded_) {
        res.success = false;
        res.failureReason = "Model not loaded";
        return res;
    }
    res.success = true;
    res.confidence = 0.85f;
    res.fluencyScore = 0.82f;
    res.relevanceScore = 0.88f;
    res.safetyScore = 0.96f;
    res.estimatedCost = 0.0f;
    res.text = "Response generated by LocalTransformer for prompt: " + request.prompt;
    return res;
}

bool LocalTransformer::available() const {
    return isLoaded_;
}

float LocalTransformer::estimateCost(const GenerationRequest& /*request*/) const {
    return 0.0f;
}

} // namespace yuki::brain::language
