#include "src/brain/language/VaeGrammarBackend.h"

namespace yuki::brain::language {

GenerationResult VaeGrammarBackend::generate(const GenerationRequest& request) {
    GenerationResult res;
    res.success = true;
    res.backend = BackendKind::VAE_GRAMMAR;
    res.backendName = name();
    res.confidence = 0.70f;
    res.fluencyScore = 0.65f;
    res.relevanceScore = 0.75f;
    res.safetyScore = 0.95f;
    res.estimatedCost = 0.0f;
    res.text = "Response generated by VaeGrammarBackend for prompt: " + request.prompt;
    return res;
}

bool VaeGrammarBackend::available() const {
    return true;
}

float VaeGrammarBackend::estimateCost(const GenerationRequest& /*request*/) const {
    return 0.0f;
}

} // namespace yuki::brain::language
